version: '3.7'

networks:
  default:
    driver: bridge

services:
  db:
    container_name: postgres
    image: postgres:11.12-alpine
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    container_name: django
    build:
      context: .
      args:
        USER_NAME: ${USER_NAME}
        USER_ID: ${USER_ID}
    command: /home/$USER_NAME/djangoapp/src/scripts/django_entrypoint.sh
    depends_on:
      - db
    ports:
      - 8000:8000
    environment:
      - POSTGRES_USER
      - USER_NAME
      - USER_ID
    volumes:
      - staticfiles:/home/${USER_NAME}/djangoapp/static
      - logs:/home/${USER_NAME}/djangoapp/logs

volumes:
  postgres_data:
  staticfiles:
  logs:
