# Generated by Django 3.2.12 on 2022-04-03 07:12

import core.utils
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid_4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Budget name')),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid_4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Category name')),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid_4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Income name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=25, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='amount')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='budgets.budget')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=core.utils.generate_uuid_4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Expense name')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='amount')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budgets.budget')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='budgets.expensecategory')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='categories',
            field=models.ManyToManyField(related_name='budgets', through='budgets.Expense', to='budgets.ExpenseCategory'),
        ),
        migrations.AddField(
            model_name='budget',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
