# Generated by Django 3.2.12 on 2022-04-03 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budget',
            options={'ordering': ('name',), 'verbose_name': 'Budget', 'verbose_name_plural': 'Budgets'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('name',), 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'ordering': ('name',), 'verbose_name': 'Expense category', 'verbose_name_plural': 'Expense categories'},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ('name',), 'verbose_name': 'Income for budget', 'verbose_name_plural': 'Incomes for budget'},
        ),
    ]
