# Generated by Django 3.2.12 on 2022-04-03 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_auto_20220403_0817'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('budget', 'name', 'category'), name='unique_expense_for_budget_and_category'),
        ),
        migrations.AddConstraint(
            model_name='income',
            constraint=models.UniqueConstraint(fields=('budget', 'name'), name='unique_income_for_budget'),
        ),
    ]
